CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

-- unique = Significa que não pode ter outro cadastro com o mesmo valor --

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR (255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255),
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(ENQ_CODIGO),
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY(URE_CODIGO),
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY(FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    OER_DESCRICAO VARCHAR(255) NOT NULL,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO (
    USU_DATA_CADASTRO, 
    USU_LOGIN,
    USU_AREA_ATUACAO, 
    USU_PROFISSAO ,
    USU_AREA_FORMACAO, 
    USU_DATANASC ,
    USU_ESTADO_CIVIL, 
    USU_ESTADO ,
    USU_ESCOLARIDADE, 
    USU_EMAIL ,
    USU_SENHA ,
    USU_NOME 
)
VALUE (
	"2025-10-01",
    "Lipadas",
    "Técnico do senai slk 1000 grau",
    "Estudante",
    "Tecnico em Desenvolvimento de Sistemas",
    "2009-05-14",
    "CASADO",
    "SP",
    "MÉDIO",
    "lipadas@gmail.com",
    "é u 7",
    "Felipe"
);

INSERT INTO USUARIO (
    USU_DATA_CADASTRO, 
    USU_LOGIN,
    USU_AREA_ATUACAO, 
    USU_PROFISSAO ,
    USU_AREA_FORMACAO, 
    USU_DATANASC ,
    USU_ESTADO_CIVIL, 
    USU_ESTADO ,
    USU_ESCOLARIDADE, 
    USU_EMAIL ,
    USU_SENHA ,
    USU_NOME 
)
VALUE (
	"2025-10-01",
    "Brunin",
    "Técnico do senai slk 1000 grau",
    "Estudante",
    "Tecnico em Desenvolvimento de Sistemas",
    "1810-07-02",
    "SOLTEIRO",
    "MG",
    "FUNDAMENTAL",
    "POROPA@GMAIL.COM",
    "fala dele",
    "Bruno"
);

INSERT INTO USUARIO (
    USU_DATA_CADASTRO, 
    USU_LOGIN,
    USU_AREA_ATUACAO, 
    USU_PROFISSAO ,
    USU_AREA_FORMACAO, 
    USU_DATANASC ,
    USU_ESTADO_CIVIL, 
    USU_ESTADO ,
    USU_ESCOLARIDADE, 
    USU_EMAIL ,
    USU_SENHA ,
    USU_NOME 
)
VALUE (
	"2025-10-01",
    "Paula",
    "Técnico do senai slk 1000 grau",
    "trabaiano",
    "Tecnico em Desenvolvimento de Sistemas",
    "2003-01-12",
    "CASADO",
    "SP",
    "MÉDIO",
    "paulim@gmail.com",
    "é u 9",
    "Paula"
);
select * from usuario;

INSERT INTO ENQUETE(
    ENQ_DATA_FINAL,
    ENQ_DATA_INICIAL,
    ENQ_DESCRICAO,
    ENQ_NOME,
    FK_USU_CODIGO
)
VALUES (
	"2026-12-25",
    "2023-12-25",
    "Natal terceirão 2026, festinha 3° A, pq é nóis que tá pai",
    "Festinha natal terceirão 2026",
    "1"
);

INSERT INTO ENQUETE(
    ENQ_DATA_FINAL,
    ENQ_DATA_INICIAL,
    ENQ_DESCRICAO,
    ENQ_NOME,
    FK_USU_CODIGO
)
VALUES (
	"2026-12-25",
    "2023-12-25",
    "Natal terceirão 2025, festinha 3° A, pq é nóis que tá pai",
    "Festinha natal terceirão 2025",
    "2"
);

INSERT INTO ENQUETE(
    ENQ_DATA_FINAL,
    ENQ_DATA_INICIAL,
    ENQ_DESCRICAO,
    ENQ_NOME,
    FK_USU_CODIGO
)
VALUES (
	"2026-12-25",
    "2023-12-25",
    "Natal terceirão 2024, festinha 3° A, pq é nóis que tá pai",
    "Festinha natal terceirão 2024",
    "3"
);

INSERT INTO USUARIO_RESPONDE_ENQUETE(
    URE_DATA,
    FK_USU_CODIGO,
    FK_ENQ_CODIGO
)
VALUES (
	"2025-10-01",
    "1",
    "1"
);

INSERT INTO USUARIO_RESPONDE_ENQUETE(
    URE_DATA,
    FK_USU_CODIGO,
    FK_ENQ_CODIGO
)
VALUES (
	"2025-10-01",
    "2",
    "2"
);

INSERT INTO USUARIO_RESPONDE_ENQUETE(
    URE_DATA,
    FK_USU_CODIGO,
    FK_ENQ_CODIGO
)
VALUES (
	"2025-10-01",
    "3",
    "3"
);
select * from USUARIO_RESPONDE_ENQUETE;

INSERT INTO PERGUNTAS(
    OER_DESCRICAO,
    FK_ENQ_CODIGO
)
VALUES (
	"Você apoia nossa festinha de natal no celtra?",
    "1"
);

INSERT INTO PERGUNTAS(
    OER_DESCRICAO,
    FK_ENQ_CODIGO
)
VALUES (
	"Você apoia nossa festinha de natal na casa da Thaiene?",
    "2"
);

INSERT INTO PERGUNTAS(
    OER_DESCRICAO,
    FK_ENQ_CODIGO
)
VALUES (
	"Você apoia nossa festinha de natal na quadra do sesi?",
    "3"
);

INSERT INTO RESPOSTAS (
    RES_DESCRICAO,
    RES_CERTA ,
    FK_PER_CODIGO 
)
VALUES (
		"Tem que ser no celtra",
        "s",
        "1"
);

INSERT INTO RESPOSTAS (
    RES_DESCRICAO,
    RES_CERTA ,
    FK_PER_CODIGO 
)
VALUES (
		"Nada haver na casa dela",
        "n",
        "2"
);

INSERT INTO RESPOSTAS (
    RES_DESCRICAO,
    RES_CERTA ,
    FK_PER_CODIGO 
)
VALUES (
		"Quadra do sesi só se for jogar bola",
        "n",
        "3"
);

select * from RESPOSTAS;