CREATE DATABASE IF NOT EXISTS BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR;
USE BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR;

CREATE TABLE IF NOT EXISTS SUPERMERCADO(
	SUP_CNPJ VARCHAR(15) PRIMARY KEY,
    SUR_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    SUP_TELEFONE VARCHAR(15) NOT NULL,
    SUP_EMAIL VARCHAR(200) NOT NULL,
    SUP_ENDERECO_LOGRADOURO VARCHAR(100) NOT NULL,
    SUP_ENDERECO_NUMERO VARCHAR(10) NOT NULL,
    SUP_ENDERECO_CIDADE VARCHAR(100) NOT NULL,
    SUP_EDERECO_ESTADO VARCHAR(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRO_CODIGO_BARRAS VARCHAR(100) NOT NULL,
    PRO_NOME VARCHAR(50) NOT NULL,
    PRO_PESO  FLOAT NOT NULL,
    PRO_QUANTIDADE INTEGER NOT NULL,
    PRO_PRECO FLOAT NOT NULL,
    PRO_DATA_VALIDADE DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSUMIDOR(
	CON_CPF VARCHAR(17) PRIMARY KEY,
    CON_NOME VARCHAR(250) NOT NULL,
    CON_TELEFONE VARCHAR(15) NOT NULL,
    CON_EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	FUN_CPF VARCHAR(15) PRIMARY KEY,
    FUN_NOME VARCHAR(255) NOT NULL,
    FUN_DATA_NASCIMENTO DATE NOT NULL,
    FUN_TELEFONE VARCHAR(18) NOT NULL,
    FUN_EMAIL VARCHAR(255) NOT NULL,
    FUN_CARTEIRA_TRABALHO VARCHAR(15) NOT NULL,
    FUN_BANCO_AGENCIA VARCHAR(20),
    FUN_BANCO_CONTA VARCHAR(20),
    FUN_DATA_ADMISSAO DATE NOT NULL,
    FUN_JORNADA_TRABALHO INTEGER NOT NULL,
    FK_SUP_CNPJ VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_SUP_CNPJ) REFERENCES SUPERMERCADO(SUP_CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SUPERMERCADO_PRODUTO(
	SPR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_SUP_CNPJ VARCHAR(15) NOT NULL,
    FK_PRO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_SUP_CNPJ) REFERENCES SUPERMERCADO(SUP_CNPJ) ON DELETE CASCADE,
    FOREIGN KEY(FK_PRO_ID) REFERENCES PRODUTO(PRO_ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO_CONSUMIDOR(
	PCO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CON_CPF VARCHAR(15) NOT NULL,
    FK_PRO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CON_CPF) REFERENCES SUPERMERCADO(SUP_CNPJ) ON DELETE CASCADE,
    FOREIGN KEY(FK_PRO_ID) REFERENCES PRODUTO(PRO_ID) ON DELETE CASCADE
);