CREATE DATABASE IF NOT EXISTS APLICATIVO_MUSICA_2ANO;
USE APLICATIVO_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TIPO_MUSICA VARCHAR(30) NOT NULL,
    QTD_MUSICA INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAPA BLOB,
    DESCRICAO VARCHAR(255),
    DATA_LANCAMENTO DATE NOT NULL,
    QTD_MUSICA INTEGER NOT NULL,
    FK_ID_ARTISTA INTEGER NOT NULL,
    FOREIGN KEY(FK_ID_ARTISTA) REFERENCES ARTISTA(ID)
);

CREATE TABLE FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LETRA VARCHAR(500),
    CAPA BLOB,
    DURACAO VARCHAR(5) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    FK_ID_ALBUM INTEGER,
    FK_ID_GENERO INTEGER,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID)
);