CREATE DATABASE IF NOT EXISTS BIBLIOTECA_DIGITAL;
USE BIBLIOTECA_DIGITAL;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(400) NOT NULL,
    DATA_PUBLICACAO DATE NOT NULL,
    FK_CPF_AUTOR VARCHAR(14),
    FOREIGN KEY(FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LEITOR_LIVRO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO INTEGER,
    FK_CPF_LEITOR VARCHAR(14),
    FOREIGN KEY(FK_ID_LIVRO) REFERENCES LIVRO_DIGITAL(ID),
    FOREIGN KEY(FK_CPF_LEITOR) REFERENCES LEITOR(CPF)
);
