CREATE DATABASE IF NOT EXISTS SISTEMA_MEDICO;
USE SISTEMA_MEDICO;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) PRIMARY KEY,
    DATA_NASCIMENTO DATE NOT NULL,
    NUM_TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LAUDO VARCHAR(400) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(30) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    HORARIO VARCHAR(7) NOT NULL,
    DESCRICAO VARCHAR(400) NOT NULL,
    FK_PACIENTE_CPF VARCHAR(15),
    FK_MEDICO_CRM VARCHAR(30),
    FOREIGN KEY(FK_PACIENTE_CPF) REFERENCES PACIENTE(CPF) ON DELETE CASCADE,
    FOREIGN KEY(FK_MEDICO_CRM) REFERENCES MEDICO(CRM) ON DELETE CASCADE
);