CREATE DATABASE IF NOT EXISTS GESTAO_MERCADO;
USE GESTAO_MERCADO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QTD INTEGER NOT NULL,
    DESCRICAO VARCHAR(255),
    NOME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(15) NOT NULL
);

CREATE TABLE PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE DATE NOT NULL,
    CUSTO DOUBLE NOT NULL,
    QTD INTEGER NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FOTO BLOB,
    FK_ID_CATEGORIA INTEGER,
    FOREIGN KEY(FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE PRODUTO_FORNECEDOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INTEGER,
    FK_CNPJ_FORNECEDOR VARCHAR(20),
    FOREIGN KEY(FK_ID_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY(FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
);