CREATE DATABASE IF NOT EXISTS GERENCIAMENTO_PROJETOS;
USE GERENCIAMENTO_PROJETOS;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRAZO DATE NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(400) NOT NULL,
    PRAZO DATE NOT NULL,
    FK_ID_PROJETO INTEGER,
    FOREIGN KEY(FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO_TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CPF_FUNCIONARIO VARCHAR(14),
    FK_ID_TAREFA INTEGER,
    FOREIGN KEY(FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY(FK_ID_TAREFA) REFERENCES TAREFA(ID)
);