CREATE DATABASE RESERVAS_PASSAGENS;
USE RESERVAS_PASSAGENS;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOO(
	NUM_VOO INTEGER PRIMARY KEY,
    ENDERECO VARCHAR(255) NOT NULL,
    DESTINO VARCHAR(255) NOT NULL,
    DATA_VOO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	NUM_ASSENTO INTEGER PRIMARY KEY,
    FILEIRA VARCHAR(3) NOT NULL,
    CLASSE VARCHAR(15) NOT NULL,
    CUSTO DOUBLE NOT NULL,
    FK_CPF_PASSAGEIRO VARCHAR(14),
    FK_NUM_VOO INTEGER,
    FOREIGN KEY(FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE,
    FOREIGN KEY(FK_NUM_VOO) REFERENCES VOO(NUM_VOO) ON DELETE CASCADE
);
